name: Build
on:
  push:
    branches:
      - master
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test -- --coverage
    - name: Report
      uses: coverallsapp/github-action@v1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./artifacts/coverage/lcov.info
    - name: Build
      run: npm run build
    - name: Deploy
      if: github.ref == 'refs/heads/master' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run release
